[window]
padding = { x = 10, y = 10 }
decorations_theme_variant = "Dark"
option_as_alt = "OnlyLeft"

[font]
normal = { family = "FiraCode Nerd Font" }
size = 12

[selection]
save_to_clipboard = true

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
persist = false
mouse = { mods = "Command", enabled = true }
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
